<a href="https://colab.research.google.com/github/shivanikasha16/ecommerce_analysis/blob/main/ecommerce_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# E-Commerce Sales & Customer Analytics Using Python

## 1. Introduction

E-commerce generates large amounts of data related to customers, orders, products, sales, marketing, and business operations. Analyzing this data can help identify patterns in customer behavior, sales performance, profitability, and operational efficiency.

This project analyzes an e-commerce dataset using Python to understand sales trends, customer characteristics, profitability, marketing performance, delivery patterns, and returns.

The project focuses on data cleaning, exploratory data analysis, descriptive statistics, statistical analysis, and data visualization.

In [ ]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings("ignore")
print("libraries imported sucessfully")

libraries imported sucessfully

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ecommerce_sales_customer_analytics_150k.csv to ecommerce_sales_customer_analytics_150k.csv

In [ ]:
df=pd.read_csv("ecommerce_sales_customer_analytics_150k.csv")
df.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8

In [ ]:
df.shape

(138116, 46)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  object
 1   order_date                138116 non-null  object
 2   order_time                138116 non-null  object
 3   order_status              138116 non-null  object
 4   sales_channel             138116 non-null  object
 5   customer_id               138116 non-null  object
 6   customer_name             138116 non-null  object
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  object
 9   customer_segment          138116 non-null  object
 10  customer_type             138116 non-null  object
 11  customer_city             138116 non-null  object
 12  customer_state            138116 non-null  object
 13  customer_country          138116 non-null  object
 14  region                    138116 non-null  object
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  object
 17  payment_status            138116 non-null  object
 18  currency                  138116 non-null  object
 19  shipping_method           138116 non-null  object
 20  warehouse                 138116 non-null  object
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  object
 24  return_status             9462 non-null    object
 25  return_reason             9462 non-null    object
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  object
 28  customer_review           113559 non-null  object
 29  marketing_channel         138116 non-null  object
 30  campaign_name             54883 non-null   object
 31  coupon_code               27614 non-null   object
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), object(27)
memory usage: 47.6+ MB

In [ ]:
df.describe()

,customer_age,customer_postal_code,delivery_days,estimated_delivery_days,customer_rating,loyalty_points_earned,loyalty_points_redeemed,quantity,gross_sales,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,customer_order_count
count,138116.000000,138116.000000,113559.000000,113559.000000,113559.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000
mean,45.862681,50210.889310,4.557772,4.298875,3.677015,103.991051,51.934128,5.615244,1375.384176,237.621614,122.462933,22.278080,1282.503575,708.903449,551.322046,45.065997,8971.639047,6.990559
std,16.467676,28569.767779,2.810012,2.594080,0.483672,115.175640,73.217692,3.371289,1291.009554,378.779459,140.939368,16.022739,1169.274669,730.044970,516.300936,13.120357,4430.506588,2.444166
min,18.000000,516.000000,0.000000,0.000000,1.600000,0.000000,0.000000,1.000000,6.310000,0.000000,0.340000,0.000000,5.800000,1.970000,-1281.590000,-59.550000,22.550000,1.000000
25%,32.000000,25509.000000,2.000000,2.000000,3.400000,17.000000,3.000000,3.000000,458.920000,26.327500,34.650000,9.820000,448.200000,207.667500,190.757500,38.880000,5713.570000,5.000000
50%,46.000000,50183.000000,4.000000,4.000000,3.700000,70.000000,25.000000,5.000000,995.730000,103.285000,77.010000,19.190000,950.760000,478.955000,408.395000,46.990000,8392.525000,7.000000
75%,60.000000,74898.000000,7.000000,6.000000,4.000000,151.000000,71.000000,8.000000,1871.200000,277.125000,156.200000,30.750000,1744.582500,953.762500,752.845000,53.770000,11651.030000,9.000000
max,74.000000,99950.000000,14.000000,10.000000,5.000000,1621.000000,1063.000000,24.000000,16051.190000,6759.020000,2091.520000,149.520000,16218.000000,9963.410000,7083.680000,77.590000,30268.440000,20.000000

In [ ]:
df.isnull().sum()

order_id                         0
order_date                       0
order_time                       0
order_status                     0
sales_channel                    0
customer_id                      0
customer_name                    0
customer_age                     0
gender                           0
customer_segment                 0
customer_type                    0
customer_city                    0
customer_state                   0
customer_country                 0
region                           0
customer_postal_code             0
payment_method                   0
payment_status                   0
currency                         0
shipping_method                  0
warehouse                        0
delivery_days                24557
estimated_delivery_days      24557
delivery_status                  0
return_status               128654
return_reason               128654
customer_rating              24557
review_sentiment             24557
customer_review              24557
marketing_channel                0
campaign_name                83233
coupon_code                 110502
loyalty_points_earned            0
loyalty_points_redeemed          0
quantity                         0
gross_sales                      0
discount_amount                  0
tax_amount                       0
shipping_cost                    0
net_sales                        0
product_cost                     0
profit                           0
profit_margin_percentage         0
customer_lifetime_value          0
is_repeat_customer               0
customer_order_count             0
dtype: int64

In [ ]:
# Number of unique values in important categorical columns

columns = [
    'return_status',
    'return_reason',
    'campaign_name',
    'delivery_status',
    'marketing_channel'
]

for col in columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(15))

--- return_status ---
return_status
NaN         128654
Returned      9462
Name: count, dtype: int64

--- return_reason ---
return_reason
NaN                        128654
Wrong Product                1237
Other                        1208
Changed Mind                 1204
Size Issue                   1182
Defective Product            1174
Late Delivery                1172
Product Not as Expected      1147
Damaged Product              1138
Name: count, dtype: int64

--- campaign_name ---
campaign_name
NaN                  83233
Default_Campaign     22989
Google_Search_Q1      2748
Google_Shopping       2746
Google_Display        2731
FB_Retargeting        2270
FB_Dynamic            2233
Friend_Invite         2232
Referral_Program      2198
FB_Prospecting        2161
Insta_Influencer      1822
Insta_Reels           1799
Insta_Stories         1773
Abandoned_Cart        1520
Weekly_Newsletter     1459
Name: count, dtype: int64

--- delivery_status ---
delivery_status
On Time      86916
Cancelled    24557
Delayed      16886
Early         9757
Name: count, dtype: int64

--- marketing_channel ---
marketing_channel
Organic Search     27742
Google Ads         20633
Direct             20515
Facebook Ads       16651
Instagram          13801
Email Marketing    11218
Referral           11191
Affiliate           6848
TikTok              5437
YouTube             4080
Name: count, dtype: int64

In [ ]:
# Missing percentage for every column

missing_percentage = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

missing_percentage

return_reason               93.149237
return_status               93.149237
coupon_code                 80.006661
campaign_name               60.263112
customer_review             17.779982
customer_rating             17.779982
estimated_delivery_days     17.779982
delivery_days               17.779982
review_sentiment            17.779982
order_id                     0.000000
order_time                   0.000000
order_status                 0.000000
sales_channel                0.000000
order_date                   0.000000
customer_country             0.000000
customer_state               0.000000
customer_city                0.000000
customer_type                0.000000
customer_segment             0.000000
gender                       0.000000
customer_age                 0.000000
customer_name                0.000000
customer_id                  0.000000
shipping_method              0.000000
warehouse                    0.000000
payment_status               0.000000
customer_postal_code         0.000000
payment_method               0.000000
currency                     0.000000
region                       0.000000
marketing_channel            0.000000
delivery_status              0.000000
loyalty_points_earned        0.000000
loyalty_points_redeemed      0.000000
quantity                     0.000000
gross_sales                  0.000000
discount_amount              0.000000
tax_amount                   0.000000
shipping_cost                0.000000
net_sales                    0.000000
product_cost                 0.000000
profit                       0.000000
profit_margin_percentage     0.000000
customer_lifetime_value      0.000000
is_repeat_customer           0.000000
customer_order_count         0.000000
dtype: float64

In [ ]:
df[df['delivery_status'] == 'Cancelled'][
    ['delivery_days',
     'estimated_delivery_days',
     'customer_rating',
     'review_sentiment',
     'customer_review']
].isnull().sum()

delivery_days              24557
estimated_delivery_days    24557
customer_rating            24557
review_sentiment           24557
customer_review            24557
dtype: int64

In [ ]:
df.groupby('delivery_status')[
    ['delivery_days', 'estimated_delivery_days', 'customer_rating']
].apply(lambda x: x.isnull().sum())

                 delivery_days  estimated_delivery_days  customer_rating
delivery_status
Cancelled                24557                    24557            24557
Delayed                      0                        0                0
Early                        0                        0                0
On Time                      0                        0                0

In [ ]:
pd.crosstab(
    df['marketing_channel'].fillna('No Channel'),
    df['campaign_name'].fillna('No Campaign')
)

campaign_name,Abandoned_Cart,Affiliate_Partner,Default_Campaign,FB_Dynamic,FB_Prospecting,FB_Retargeting,Friend_Invite,Google_Display,Google_Search_Q1,Google_Shopping,Influencer_Program,Insta_Influencer,Insta_Reels,Insta_Stories,No Campaign,Promo_Email,Referral_Program,Weekly_Newsletter
marketing_channel,,,,,,,,,,,,,,,,,,
Affiliate,0,1339,0,0,0,0,0,0,0,0,1404,0,0,0,4105,0,0,0
Direct,0,0,8182,0,0,0,0,0,0,0,0,0,0,0,12333,0,0,0
Email Marketing,1520,0,0,0,0,0,0,0,0,0,0,0,0,0,6780,1459,0,1459
Facebook Ads,0,0,0,2233,2161,2270,0,0,0,0,0,0,0,0,9987,0,0,0
Google Ads,0,0,0,0,0,0,0,2731,2748,2746,0,0,0,0,12408,0,0,0
Instagram,0,0,0,0,0,0,0,0,0,0,0,1822,1799,1773,8407,0,0,0
Organic Search,0,0,11009,0,0,0,0,0,0,0,0,0,0,0,16733,0,0,0
Referral,0,0,0,0,0,0,2232,0,0,0,0,0,0,0,6761,0,2198,0
TikTok,0,0,2201,0,0,0,0,0,0,0,0,0,0,0,3236,0,0,0
YouTube,0,0,1597,0,0,0,0,0,0,0,0,0,0,0,2483,0,0,0

In [ ]:
campaign_check = df.groupby(
    df['campaign_name'].isna()
)['marketing_channel'].value_counts()

campaign_check

campaign_name  marketing_channel
False          Organic Search       11009
               Google Ads            8225
               Direct                8182
               Facebook Ads          6664
               Instagram             5394
               Email Marketing       4438
               Referral              4430
               Affiliate             2743
               TikTok                2201
               YouTube               1597
True           Organic Search       16733
               Google Ads           12408
               Direct               12333
               Facebook Ads          9987
               Instagram             8407
               Email Marketing       6780
               Referral              6761
               Affiliate             4105
               TikTok                3236
               YouTube               2483
Name: count, dtype: int64

In [ ]:
df[df['campaign_name'].isna()]['marketing_channel'].value_counts()

marketing_channel
Organic Search     16733
Google Ads         12408
Direct             12333
Facebook Ads        9987
Instagram           8407
Email Marketing     6780
Referral            6761
Affiliate           4105
TikTok              3236
YouTube             2483
Name: count, dtype: int64

In [ ]:
campaign_by_channel = (
    df.groupby('marketing_channel')['campaign_name']
    .apply(lambda x: x.notna().sum())
)

campaign_by_channel

marketing_channel
Affiliate           2743
Direct              8182
Email Marketing     4438
Facebook Ads        6664
Google Ads          8225
Instagram           5394
Organic Search     11009
Referral            4430
TikTok              2201
YouTube             1597
Name: campaign_name, dtype: int64

In [ ]:
campaign_percentage = (
    df.groupby('marketing_channel')['campaign_name']
    .apply(lambda x: x.notna().mean() * 100)
    .sort_values(ascending=False)
)

campaign_percentage

marketing_channel
TikTok             40.481883
Affiliate          40.055491
Facebook Ads       40.021620
Direct             39.883012
Google Ads         39.863326
Organic Search     39.683512
Referral           39.585381
Email Marketing    39.561419
YouTube            39.142157
Instagram          39.084124
Name: campaign_name, dtype: float64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['order_id'].duplicated().sum()

np.int64(0)

In [ ]:
df['order_id'].nunique()

138116

In [ ]:
df.dtypes

order_id                     object
order_date                   object
order_time                   object
order_status                 object
sales_channel                object
customer_id                  object
customer_name                object
customer_age                  int64
gender                       object
customer_segment             object
customer_type                object
customer_city                object
customer_state               object
customer_country             object
region                       object
customer_postal_code          int64
payment_method               object
payment_status               object
currency                     object
shipping_method              object
warehouse                    object
delivery_days               float64
estimated_delivery_days     float64
delivery_status              object
return_status                object
return_reason                object
customer_rating             float64
review_sentiment             object
customer_review              object
marketing_channel            object
campaign_name                object
coupon_code                  object
loyalty_points_earned         int64
loyalty_points_redeemed       int64
quantity                      int64
gross_sales                 float64
discount_amount             float64
tax_amount                  float64
shipping_cost               float64
net_sales                   float64
product_cost                float64
profit                      float64
profit_margin_percentage    float64
customer_lifetime_value     float64
is_repeat_customer             bool
customer_order_count          int64
dtype: object

In [ ]:
df.dtypes.value_counts()

object     27
float64    12
int64       6
bool        1
Name: count, dtype: int64

In [ ]:
df.nunique().sort_values()

return_status                    1
is_repeat_customer               2
review_sentiment                 3
customer_type                    3
gender                           3
customer_segment                 4
order_status                     4
payment_status                   4
shipping_method                  4
delivery_status                  4
sales_channel                    4
region                           5
customer_country                 7
currency                         7
payment_method                   7
return_reason                    8
marketing_channel               10
estimated_delivery_days         11
delivery_days                   15
campaign_name                   17
customer_order_count            19
warehouse                       19
quantity                        24
customer_review                 25
customer_rating                 35
customer_state                  38
coupon_code                     40
customer_age                    57
loyalty_points_redeemed        642
loyalty_points_earned          846
order_date                    1826
profit_margin_percentage      7947
shipping_cost                11973
customer_city                15516
customer_name                21564
customer_postal_code         22117
customer_lifetime_value      24752
customer_id                  24911
tax_amount                   43093
discount_amount              58437
order_time                   68991
product_cost                 88450
profit                       91021
gross_sales                 100130
net_sales                   112204
order_id                    138116
dtype: int64

In [ ]:
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].nunique(), "unique values")
    print(df[col].dropna().unique()[:20])

--- order_id ---
138116 unique values
['ORD-301242' 'ORD-773460' 'ORD-449374' 'ORD-567636' 'ORD-820028'
 'ORD-208728' 'ORD-686230' 'ORD-480470' 'ORD-417329' 'ORD-961581'
 'ORD-560607' 'ORD-145098' 'ORD-163733' 'ORD-825133' 'ORD-475363'
 'ORD-968844' 'ORD-810046' 'ORD-498913' 'ORD-652783' 'ORD-537228']

--- order_date ---
1826 unique values
['2023-11-06' '2025-12-24' '2021-07-05' '2023-01-21' '2022-05-13'
 '2021-02-10' '2021-05-03' '2022-10-13' '2022-12-06' '2023-09-19'
 '2024-03-15' '2022-08-25' '2024-03-03' '2022-09-04' '2024-07-05'
 '2022-10-20' '2021-01-04' '2025-03-24' '2024-12-09' '2025-04-26']

--- order_time ---
68991 unique values
['16:37:47' '01:22:36' '14:24:21' '07:20:26' '09:46:21' '10:05:47'
 '02:55:44' '21:19:50' '17:22:52' '18:38:32' '18:20:55' '10:30:17'
 '04:27:09' '22:09:12' '19:49:42' '21:59:35' '02:13:38' '19:38:47'
 '04:27:49' '11:19:10']

--- order_status ---
4 unique values
['Completed' 'Pending' 'Cancelled' 'Returned']

--- sales_channel ---
4 unique values
['Mobile App' 'Website' 'Social Media' 'Marketplace']

--- customer_id ---
24911 unique values
['CUST-003102' 'CUST-003124' 'CUST-012496' 'CUST-023928' 'CUST-012730'
 'CUST-021468' 'CUST-023734' 'CUST-020081' 'CUST-011921' 'CUST-016600'
 'CUST-021779' 'CUST-013168' 'CUST-002075' 'CUST-018476' 'CUST-012765'
 'CUST-001436' 'CUST-000109' 'CUST-022079' 'CUST-000860' 'CUST-012835']

--- customer_name ---
21564 unique values
['Jasmine Ryan' 'Scott Chase' 'Marc Wheeler' 'Jennifer Smith'
 'Jessica Wang' 'Dominique Odom' 'Julian Marshall' 'Michael Prince'
 'Gary Higgins' 'Patricia Gay' 'Christie Sharp' 'Austin Romero'
 'Donald Leon' 'Amy Garcia' 'Brent Huber' 'Gabrielle Valencia'
 'Kyle Baker' 'Benjamin Johnson' 'John Murphy' 'Timothy Zimmerman']

--- gender ---
3 unique values
['Male' 'Female' 'Non-Binary']

--- customer_segment ---
4 unique values
['Consumer' 'Premium' 'VIP' 'Business']

--- customer_type ---
3 unique values
['Loyal' 'Returning' 'New']

--- customer_city ---
15516 unique values
['Lake Williamberg' 'Kristyport' 'Singletonhaven' 'Wigginsstad'
 'New Michaelton' 'Morrisonfort' 'Brianville' 'Dominguezbury' 'Lake Mary'
 'Lake Cheyenneton' 'Markmouth' 'Lisaside' 'Sancheztown' 'New Andreaberg'
 'Cruzton' 'Bobbybury' 'North Ericport' 'Christopherfurt' 'Port Kimberly'
 'Katrinaville']

--- customer_state ---
38 unique values
['Texas' 'Baden-Württemberg' 'New York' 'North Carolina' 'Gujarat'
 'Alberta' 'Quebec' 'Pennsylvania' 'Hesse' 'Illinois' 'England' 'Georgia'
 'Wales' 'Michigan' 'Victoria' 'Bavaria' 'Northern Ireland' 'Dubai' 'Ohio'
 'North Rhine']

--- customer_country ---
7 unique values
['USA' 'Germany' 'India' 'Canada' 'UK' 'Australia' 'UAE']

--- region ---
5 unique values
['South' 'East' 'West' 'Central' 'North']

--- payment_method ---
7 unique values
['Digital Wallet' 'Debit Card' 'Cash on Delivery' 'Credit Card' 'PayPal'
 'Buy Now Pay Later' 'Bank Transfer']

--- payment_status ---
4 unique values
['Paid' 'Pending' 'Failed' 'Refunded']

--- currency ---
7 unique values
['USD' 'EUR' 'INR' 'CAD' 'GBP' 'AUD' 'AED']

--- shipping_method ---
4 unique values
['Standard' 'Economy' 'Express' 'Same Day']

--- warehouse ---
19 unique values
['WH-003' 'WH-005' 'WH-015' 'WH-010' 'WH-013' 'WH-018' 'WH-006' 'WH-017'
 'WH-009' 'WH-001' 'WH-016' 'WH-008' 'WH-004' 'WH-014' 'WH-002' 'WH-007'
 'WH-011' 'WH-019' 'WH-012']

--- delivery_status ---
4 unique values
['On Time' 'Delayed' 'Cancelled' 'Early']

--- return_status ---
1 unique values
['Returned']

--- return_reason ---
8 unique values
['Wrong Product' 'Defective Product' 'Size Issue' 'Damaged Product'
 'Product Not as Expected' 'Other' 'Changed Mind' 'Late Delivery']

--- review_sentiment ---
3 unique values
['Positive' 'Neutral' 'Negative']

--- customer_review ---
25 unique values
['Satisfied with the purchase.' 'Good value for money.'
 'Good product. Works as expected.' 'Mixed feelings about this purchase.'
 'Average product. Could be better.'
 'Met my expectations. Would recommend.'
 "Not what I expected but it's okay." 'Quality could be improved.'
 'Decent quality for the price.' 'Product has some issues but it works.'
 'Product is okay, nothing special but works.'
 'Excellent customer service and amazing product.'
 'Absolutely love this product! Exceeded all expectations.'
 'Perfect product for my needs. Will buy again.'
 'Product arrived quickly and works perfectly.'
 'Great quality and fast shipping. Highly recommend!'
 "Best purchase I've made this year!"
 'Very happy with the quality and price.'
 'Very disappointed with this product.'
 'Super satisfied with everything. Great value.']

--- marketing_channel ---
10 unique values
['Direct' 'YouTube' 'Email Marketing' 'Organic Search' 'Referral'
 'Google Ads' 'Facebook Ads' 'TikTok' 'Instagram' 'Affiliate']

--- campaign_name ---
17 unique values
['Default_Campaign' 'Friend_Invite' 'Google_Shopping' 'FB_Dynamic'
 'FB_Retargeting' 'Weekly_Newsletter' 'Abandoned_Cart' 'Insta_Stories'
 'Google_Display' 'Insta_Influencer' 'Referral_Program' 'Insta_Reels'
 'FB_Prospecting' 'Google_Search_Q1' 'Promo_Email' 'Affiliate_Partner'
 'Influencer_Program']

--- coupon_code ---
40 unique values
['SAVE31' 'SAVE15' 'SAVE30' 'SAVE45' 'SAVE34' 'SAVE27' 'SAVE41' 'SAVE10'
 'SAVE44' 'SAVE16' 'SAVE38' 'SAVE18' 'SAVE42' 'SAVE22' 'SAVE23' 'SAVE33'
 'SAVE19' 'SAVE48' 'SAVE39' 'SAVE21']

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['order_time'] = pd.to_datetime(df['order_time']).dt.time

In [ ]:
print("Minimum date:", df['order_date'].min())
print("Maximum date:", df['order_date'].max())

Minimum date: 2021-01-01 00:00:00
Maximum date: 2025-12-31 00:00:00

In [ ]:
df['order_date'].value_counts().sort_index().head(10)

order_date
2021-01-01    65
2021-01-02    58
2021-01-03    63
2021-01-04    70
2021-01-05    71
2021-01-06    57
2021-01-07    43
2021-01-08    61
2021-01-09    73
2021-01-10    60
Name: count, dtype: int64

In [ ]:
df['order_date'].value_counts().sort_index().tail(10)

order_date
2025-12-22    120
2025-12-23    122
2025-12-24    115
2025-12-25    118
2025-12-26    115
2025-12-27     92
2025-12-28     98
2025-12-29     92
2025-12-30    143
2025-12-31     96
Name: count, dtype: int64

In [ ]:
pd.to_datetime(df['order_date'], errors='coerce').isna().sum()

np.int64(0)

In [ ]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
order_date,138116,2023-07-21 10:11:31.662081280,2021-01-01 00:00:00,2022-04-20 00:00:00,2023-08-01 00:00:00,2024-10-29 00:00:00,2025-12-31 00:00:00,NaN
customer_age,138116.0,45.862681,18.0,32.0,46.0,60.0,74.0,16.467676
customer_postal_code,138116.0,50210.88931,516.0,25509.0,50183.0,74898.0,99950.0,28569.767779
delivery_days,113559.0,4.557772,0.0,2.0,4.0,7.0,14.0,2.810012
estimated_delivery_days,113559.0,4.298875,0.0,2.0,4.0,6.0,10.0,2.59408
customer_rating,113559.0,3.677015,1.6,3.4,3.7,4.0,5.0,0.483672
loyalty_points_earned,138116.0,103.991051,0.0,17.0,70.0,151.0,1621.0,115.17564
loyalty_points_redeemed,138116.0,51.934128,0.0,3.0,25.0,71.0,1063.0,73.217692
quantity,138116.0,5.615244,1.0,3.0,5.0,8.0,24.0,3.371289
gross_sales,138116.0,1375.384176,6.31,458.92,995.73,1871.2,16051.19,1291.009554
discount_amount,138116.0,237.621614,0.0,26.3275,103.285,277.125,6759.02,378.779459
tax_amount,138116.0,122.462933,0.34,34.65,77.01,156.2,2091.52,140.939368
shipping_cost,138116.0,22.27808,0.0,9.82,19.19,30.75,149.52,16.022739
net_sales,138116.0,1282.503575,5.8,448.2,950.76,1744.5825,16218.0,1169.274669
product_cost,138116.0,708.903449,1.97,207.6675,478.955,953.7625,9963.41,730.04497
profit,138116.0,551.322046,-1281.59,190.7575,408.395,752.845,7083.68,516.300936
profit_margin_percentage,138116.0,45.065997,-59.55,38.88,46.99,53.77,77.59,13.120357
customer_lifetime_value,138116.0,8971.639047,22.55,5713.57,8392.525,11651.03,30268.44,4430.506588
customer_order_count,138116.0,6.990559,1.0,5.0,7.0,9.0,20.0,2.444166

In [ ]:
df_clean = df.copy()

In [ ]:
df_clean['order_date'] = pd.to_datetime(
    df_clean['order_date'],
    errors='coerce'
)

In [ ]:
df_clean['customer_postal_code'] = (
    df_clean['customer_postal_code'].astype(str)
)

In [ ]:
df_clean['return_status'] = (
    df_clean['return_status'].fillna('Not Returned')
)

df_clean['return_reason'] = (
    df_clean['return_reason'].fillna('No Return')
)

df_clean['campaign_name'] = (
    df_clean['campaign_name'].fillna('No Specific Campaign')
)

In [ ]:
df_clean.isnull().sum()

order_id                         0
order_date                       0
order_time                       0
order_status                     0
sales_channel                    0
customer_id                      0
customer_name                    0
customer_age                     0
gender                           0
customer_segment                 0
customer_type                    0
customer_city                    0
customer_state                   0
customer_country                 0
region                           0
customer_postal_code             0
payment_method                   0
payment_status                   0
currency                         0
shipping_method                  0
warehouse                        0
delivery_days                24557
estimated_delivery_days      24557
delivery_status                  0
return_status                    0
return_reason                    0
customer_rating              24557
review_sentiment             24557
customer_review              24557
marketing_channel                0
campaign_name                    0
coupon_code                 110502
loyalty_points_earned            0
loyalty_points_redeemed          0
quantity                         0
gross_sales                      0
discount_amount                  0
tax_amount                       0
shipping_cost                    0
net_sales                        0
product_cost                     0
profit                           0
profit_margin_percentage         0
customer_lifetime_value          0
is_repeat_customer               0
customer_order_count             0
dtype: int64

In [ ]:
df_clean['coupon_code'].value_counts(dropna=False)

coupon_code
NaN       110502
SAVE39       731
SAVE49       727
SAVE40       719
SAVE12       716
SAVE33       715
SAVE26       712
SAVE25       711
SAVE15       709
SAVE36       709
SAVE46       707
SAVE44       704
SAVE21       704
SAVE27       702
SAVE22       702
SAVE13       701
SAVE17       701
SAVE43       699
SAVE18       699
SAVE19       693
SAVE31       693
SAVE42       691
SAVE20       690
SAVE32       687
SAVE41       685
SAVE11       683
SAVE48       682
SAVE37       681
SAVE38       681
SAVE34       679
SAVE16       677
SAVE35       675
SAVE28       674
SAVE23       674
SAVE47       673
SAVE30       670
SAVE45       665
SAVE14       662
SAVE24       656
SAVE29       641
SAVE10       634
Name: count, dtype: int64

In [ ]:
df_clean.groupby('coupon_code', dropna=False)['discount_amount'].mean().sort_values(ascending=False)

coupon_code
SAVE25    255.223263
SAVE38    252.849809
SAVE40    250.095841
SAVE20    249.481029
SAVE39    248.723611
SAVE36    247.265219
SAVE43    246.900114
SAVE23    245.302774
SAVE44    245.129773
SAVE15    243.847884
SAVE13    243.130542
SAVE24    242.809817
SAVE16    242.236470
SAVE42    242.214805
SAVE33    241.835748
SAVE29    240.822465
SAVE35    240.275393
SAVE41    240.107679
SAVE26    239.620267
SAVE37    238.993906
SAVE12    238.572291
NaN       238.071515
SAVE17    236.314593
SAVE14    236.121828
SAVE22    235.787721
SAVE19    235.288124
SAVE46    235.076620
SAVE31    233.109740
SAVE45    232.206917
SAVE10    229.191640
SAVE49    229.139464
SAVE28    229.105534
SAVE32    225.535138
SAVE18    225.419714
SAVE27    222.304801
SAVE47    219.375156
SAVE21    218.135369
SAVE11    217.754612
SAVE30    215.298313
SAVE48    210.898460
SAVE34    207.719985
Name: discount_amount, dtype: float64

In [ ]:
df_clean.groupby(
    df_clean['coupon_code'].isna()
)['discount_amount'].agg(['count', 'mean', 'min', 'max'])

              count        mean  min      max
coupon_code
False         27614  235.821261  0.0  5046.32
True         110502  238.071515  0.0  6759.02

In [ ]:
pd.crosstab(
    df_clean['coupon_code'].isna(),
    df_clean['discount_amount'] == 0
)

discount_amount  False  True
coupon_code
False            23986   3628
True             96266  14236

In [ ]:
df_clean['coupon_code'] = df_clean['coupon_code'].fillna('No Coupon Recorded')

In [ ]:
df_clean['coupon_code'].isnull().sum()

np.int64(0)

In [ ]:
df_clean.duplicated().sum()

np.int64(0)

In [ ]:
df_clean['order_id'].duplicated().sum()

np.int64(0)

In [ ]:
df_clean.dtypes

order_id                            object
order_date                  datetime64[ns]
order_time                          object
order_status                        object
sales_channel                       object
customer_id                         object
customer_name                       object
customer_age                         int64
gender                              object
customer_segment                    object
customer_type                       object
customer_city                       object
customer_state                      object
customer_country                    object
region                              object
customer_postal_code                object
payment_method                      object
payment_status                      object
currency                            object
shipping_method                     object
warehouse                           object
delivery_days                      float64
estimated_delivery_days            float64
delivery_status                     object
return_status                       object
return_reason                       object
customer_rating                    float64
review_sentiment                    object
customer_review                     object
marketing_channel                   object
campaign_name                       object
coupon_code                         object
loyalty_points_earned                int64
loyalty_points_redeemed              int64
quantity                             int64
gross_sales                        float64
discount_amount                    float64
tax_amount                         float64
shipping_cost                      float64
net_sales                          float64
product_cost                       float64
profit                             float64
profit_margin_percentage           float64
customer_lifetime_value            float64
is_repeat_customer                    bool
customer_order_count                 int64
dtype: object

In [ ]:
df_clean.dtypes

order_id                            object
order_date                  datetime64[ns]
order_time                          object
order_status                        object
sales_channel                       object
customer_id                         object
customer_name                       object
customer_age                         int64
gender                              object
customer_segment                    object
customer_type                       object
customer_city                       object
customer_state                      object
customer_country                    object
region                              object
customer_postal_code                object
payment_method                      object
payment_status                      object
currency                            object
shipping_method                     object
warehouse                           object
delivery_days                      float64
estimated_delivery_days            float64
delivery_status                     object
return_status                       object
return_reason                       object
customer_rating                    float64
review_sentiment                    object
customer_review                     object
marketing_channel                   object
campaign_name                       object
coupon_code                         object
loyalty_points_earned                int64
loyalty_points_redeemed              int64
quantity                             int64
gross_sales                        float64
discount_amount                    float64
tax_amount                         float64
shipping_cost                      float64
net_sales                          float64
product_cost                       float64
profit                             float64
profit_margin_percentage           float64
customer_lifetime_value            float64
is_repeat_customer                    bool
customer_order_count                 int64
dtype: object